### ISSUE TITLE
Need a draft commarch team proposal

### ISSUE THREAD

**Issue by ghost** [adf5051/hfoss#5]
A week ago, you were asked to identify at least two projects to consider analyzing for the community architecture assignment. Please provide these in the form of a draft team proposal.

There are many acceptable ways to communicate this to your instructor, but submitting a commit in a drafts folder on a feature branch of this repository would be acceptable.

**Comment by adf5051** [comment]
Page can be found at https://adf5051.github.io/hfoss/ and the branch is gh-pages

**Comment by adf5051** [comment]
The repo for the research is found at https://github.com/adf5051/CommarchReport
